spring.application.name=init
server.port=8080
server.servlet.context-path=/raw
management.endpoints.web.exposure.include=*

# --------------------- cache inv

spring.web.resources.cache.period=0
spring.web.resources.chain.cache=false
spring.thymeleaf.cache=false
spring.mvc.cache-control.no-store=true
# -------------------------
management.info.env.enabled=true
info.app.name=section1
info.app.description=seciton1des
info.app.version=0.0.0.1

vishnu.name=Vishnu
swathi.name=Swathi

# -------------- user pass-----------------

spring.security.user.name=user
spring.security.user.password=1