spring.application.name=init
server.port=8000
management.endpoints.web.exposure.include=*
management.info.env.enabled=true
info.app.name=section1
info.app.description=seciton1des
info.app.version=0.0.0.1

vishnu.name=Vishnu
swathi.name=Swathi